/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Lenovo
 */
public class Lulusan extends javax.swing.JFrame {

    /**
     * Creates new form Lulusan
     */
    public Lulusan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Txtsiswa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Txtpass = new javax.swing.JTextField();
        Txtnama = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Txttgllahir = new javax.swing.JTextField();
        Txtgender = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Bsimpan1 = new javax.swing.JButton();
        Bedit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data Lulusan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Id");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 68, 80, -1));

        Txtsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtsiswaActionPerformed(evt);
            }
        });
        jPanel2.add(Txtsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 60, -1));

        jLabel16.setText("Nama");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 99, -1, -1));

        Txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtpassActionPerformed(evt);
            }
        });
        jPanel2.add(Txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 250, -1));

        Txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnamaActionPerformed(evt);
            }
        });
        jPanel2.add(Txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 250, -1));

        jLabel17.setText("Tanggal Lahir");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 131, -1, -1));

        jLabel18.setText("Jenjang");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 171, -1, -1));

        Txttgllahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxttgllahirActionPerformed(evt);
            }
        });
        jPanel2.add(Txttgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 250, -1));

        Txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtgenderActionPerformed(evt);
            }
        });
        jPanel2.add(Txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 130, -1));

        jLabel19.setText("Program Studi");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 208, 90, -1));

        Bsimpan1.setText("Simpan");
        Bsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsimpan1ActionPerformed(evt);
            }
        });
        jPanel2.add(Bsimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        Bedit1.setText("Edit");
        Bedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bedit1ActionPerformed(evt);
            }
        });
        jPanel2.add(Bedit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtsiswaActionPerformed

    private void TxtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtpassActionPerformed

    private void TxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnamaActionPerformed

    private void TxttgllahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxttgllahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxttgllahirActionPerformed

    private void TxtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtgenderActionPerformed

    private void Bsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsimpan1ActionPerformed
        // TODO add your handling code here:
        String id_siswa, password, nama_siswa, tgl_lahir, gender ;
        int hasil;
        id_siswa = Txtsiswa.getText();
        password = Txtpass.getText();
        nama_siswa = Txtnama.getText();
        tgl_lahir = Txttgllahir.getText();
        gender = Txtgender.getText();

        ExecuteSiswa exSwa = new ExecuteSiswa();
        siswa swa = new siswa (id_siswa, password, nama_siswa, tgl_lahir, gender);
        hasil = exSwa.insertSwa(swa);

        setFieldEmpty();
        tampilsiswa();
    }//GEN-LAST:event_Bsimpan1ActionPerformed

    private void Bedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bedit1ActionPerformed
        // TODO add your handling code here:
        String id_siswa, password, nama_siswa, tgl_lahir, gender ;
        int hasil;
        id_siswa = Txtsiswa.getText();
        password = Txtpass.getText();
        nama_siswa = Txtnama.getText();
        tgl_lahir = Txttgllahir.getText();
        gender = Txtgender.getText();

        ExecuteSiswa exSwa = new ExecuteSiswa();
        siswa swa = new siswa (id_siswa, password, nama_siswa, tgl_lahir, gender);
        hasil = exSwa.updatetSwa(swa);

        setFieldEmpty();
        tampilsiswa();

    }//GEN-LAST:event_Bedit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lulusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lulusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lulusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lulusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lulusan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bedit1;
    private javax.swing.JButton Bsimpan1;
    private javax.swing.JTextField Txtgender;
    private javax.swing.JTextField Txtnama;
    private javax.swing.JTextField Txtpass;
    private javax.swing.JTextField Txtsiswa;
    private javax.swing.JTextField Txttgllahir;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
