/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Lulusan;
import controller.ExecuteLulusan;

/**
 *
 * @author Lenovo
 */
public class PLulusan extends javax.swing.JFrame {

    /**
     * Creates new form Lulusan
     */
    public PLulusan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Txtid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Txtnama = new javax.swing.JTextField();
        Txtjenjang = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Txttgllahir = new javax.swing.JTextField();
        Txtps = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Bsimpan1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Txtemail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Txtalamat = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Txthp = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Txtipk = new javax.swing.JTextField();
        Bhapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data Lulusan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel2.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel2HierarchyChanged(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Id");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 57, 80, -1));

        Txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtidActionPerformed(evt);
            }
        });
        jPanel2.add(Txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 96, -1));

        jLabel16.setText("Nama");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnamaActionPerformed(evt);
            }
        });
        jPanel2.add(Txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 250, -1));

        Txtjenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtjenjangActionPerformed(evt);
            }
        });
        jPanel2.add(Txtjenjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 165, 250, -1));

        jLabel17.setText("Tanggal Lahir");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 131, -1, -1));

        jLabel18.setText("Jenjang");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 165, -1, -1));

        Txttgllahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxttgllahirActionPerformed(evt);
            }
        });
        jPanel2.add(Txttgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 250, -1));

        Txtps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtpsActionPerformed(evt);
            }
        });
        jPanel2.add(Txtps, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 202, 250, -1));

        jLabel19.setText("Program Studi");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 205, 90, -1));

        Bsimpan1.setText("Simpan");
        Bsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsimpan1ActionPerformed(evt);
            }
        });
        jPanel2.add(Bsimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 414, -1, -1));

        jLabel20.setText("Email");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 245, 90, -1));

        Txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtemailActionPerformed(evt);
            }
        });
        jPanel2.add(Txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 242, 250, -1));

        jLabel21.setText("Alamat");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 277, 90, 29));

        Txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtalamatActionPerformed(evt);
            }
        });
        jPanel2.add(Txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 277, 250, -1));

        jLabel22.setText("No_Hp");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 313, 90, 29));

        Txthp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxthpActionPerformed(evt);
            }
        });
        jPanel2.add(Txthp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 316, 166, -1));

        jLabel23.setText("IPK");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 355, 90, 29));
        jPanel2.add(Txtipk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 358, 55, -1));

        Bhapus.setText("Hapus");
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });
        jPanel2.add(Bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 414, -1, -1));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Lulusan");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtidActionPerformed

    private void TxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnamaActionPerformed

    private void TxtjenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtjenjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtjenjangActionPerformed

    private void TxttgllahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxttgllahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxttgllahirActionPerformed

    private void TxtpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtpsActionPerformed

    private void Bsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsimpan1ActionPerformed
        // TODO add your handling code here:
        String id_lulusan, nama_lulusan, tanggal_lahir, jenjang, program_studi, email, alamat, no_tlp, ipk ;
        int hasil;
        id_lulusan = Txtid.getText();
        nama_lulusan = Txtnama.getText();
        tanggal_lahir = Txttgllahir.getText();
        jenjang = Txtjenjang.getText();
        program_studi = Txtps.getText();
        email = Txtemail.getText();
        alamat = Txtalamat.getText();
        no_tlp = Txthp.getText();
        ipk = Txtipk.getText();

        ExecuteLulusan exLsn = new ExecuteLulusan();
        Lulusan lsn = new Lulusan (id_lulusan, nama_lulusan, tanggal_lahir, jenjang, program_studi, email, alamat, no_tlp, ipk);
        hasil = exLsn.insertLsn(lsn);
        setFieldEmpty();
        

    }//GEN-LAST:event_Bsimpan1ActionPerformed

    private void TxtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtemailActionPerformed

    private void TxtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtalamatActionPerformed

    private void TxthpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxthpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxthpActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        // TODO add your handling code here:
        Txtid.setText("");
        Txtid.setText("");
        Txtnama.setText("");
        Txttgllahir.setText("");
        Txtjenjang.setText("");
        Txtps.setText("");
        Txtemail.setText("");
        Txtalamat.setText("");
        Txthp.setText("");
        Txtipk.setText("");
        
    }//GEN-LAST:event_BhapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new PPekerjaan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel2HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel2HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2HierarchyChanged

     private void setFieldEmpty(){
         Txtid.setText("");
        Txtid.setText("");
        Txtnama.setText("");
        Txttgllahir.setText("");
        Txtjenjang.setText("");
        Txtps.setText("");
        Txtemail.setText("");
        Txtalamat.setText("");
        Txthp.setText("");
        Txtipk.setText("");
          
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PLulusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PLulusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PLulusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PLulusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PLulusan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bhapus;
    private javax.swing.JButton Bsimpan1;
    private javax.swing.JTextField Txtalamat;
    private javax.swing.JTextField Txtemail;
    private javax.swing.JTextField Txthp;
    private javax.swing.JTextField Txtid;
    private javax.swing.JTextField Txtipk;
    private javax.swing.JTextField Txtjenjang;
    private javax.swing.JTextField Txtnama;
    private javax.swing.JTextField Txtps;
    private javax.swing.JTextField Txttgllahir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
